#! /bin/sh

$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &



bspc monitor eDP-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width         1
bspc config focused_border_color "#76910d"
bspc config active_border_color  "#185591"

# bspc config normal_border_color  "#E5C07B"
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

setxkbmap -variant intl
picom --experimental-backends &
feh -z --bg-fill  /home/malvaloca/Downloads/images/*
