#! /bin/sh

$HOME/.config/polybar/launch.sh &
pgrep -x sxhkd > /dev/null || sxhkd &



bspc monitor eDP-1 -d I II III
bspc monitor DP-1 -d IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width         1
#bspc config focused_border_color "#fb8b24"
bspc config focused_border_color "#0fdb12"
# bspc config focused_border_color "#f92222"

# bspc config active_border_color  "#5f0f40"

# bspc config normal_border_color  "#E56b6f"
bspc config window_gap           20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

setxkbmap -variant intl
picom --experimental-backends &
feh -z --bg-fill  /home/malvaloca/Downloads/images/*
dunst &
wmname LG3D
